/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper */

#ifndef _Included_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
#define _Included_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
 * Method:    findLanguage
 * Signature: (Ljava/lang/String;)Lcz/vutbr/fit/knot/NNetLanguageIdentifierWrapper/Result;
 */
JNIEXPORT jobject JNICALL Java_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper_findLanguage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
 * Method:    findTopNMostFreqLangs
 * Signature: (Ljava/lang/String;I)[Lcz/vutbr/fit/knot/NNetLanguageIdentifierWrapper/Result;
 */
JNIEXPORT jobjectArray JNICALL Java_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper_findTopNMostFreqLangs
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
 * Method:    getUnknown
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper_getUnknown
  (JNIEnv *, jclass);

/*
 * Class:     cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
 * Method:    getMinNumBytesToConsider
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper_getMinNumBytesToConsider
  (JNIEnv *, jclass);

/*
 * Class:     cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
 * Method:    getMaxNumBytesToConsider
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper_getMaxNumBytesToConsider
  (JNIEnv *, jclass);

/*
 * Class:     cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
 * Method:    getMaxNumInputBytesToConsider
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper_getMaxNumInputBytesToConsider
  (JNIEnv *, jclass);

/*
 * Class:     cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
 * Method:    getReliabilityThreshold
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper_getReliabilityThreshold
  (JNIEnv *, jclass);

/*
 * Class:     cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
 * Method:    getReliabilityHrBsThreshold
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper_getReliabilityHrBsThreshold
  (JNIEnv *, jclass);

/*
 * Class:     cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
 * Method:    newNNetLanguageIdentifier
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper_newNNetLanguageIdentifier__
  (JNIEnv *, jclass);

/*
 * Class:     cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
 * Method:    newNNetLanguageIdentifier
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper_newNNetLanguageIdentifier__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper
 * Method:    deleteNNetLanguageIdentifier
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cz_vutbr_fit_knot_NNetLanguageIdentifierWrapper_deleteNNetLanguageIdentifier
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
